---
title: "Replicability of item dropping"
author: "Ian Hussey"
date: "`r format(Sys.time(), '%d %B %Y')`"
output:
  html_document:
    code_folding: hide
    highlight: haddock
    theme: flatly
    toc: yes
    toc_float: yes
---

Outputs are lists of data frames, each resampled from the full dataset.

```{r, include=FALSE}
knitr::opts_chunk$set(message=FALSE,
                      warning=FALSE)
```

```{r}

# dependencies
library(tidyverse)
library(lavaan)
library(semTools)
library(knitr)
library(kableExtra)
library(moments)
library(plotrix)
library(lubridate)
library(psych)

# functions
# rounds all numeric variables in a dataframe to the desired number of places. Non-numeric variables will be ignored.
round_df <- function(df, digits) {
  mutate_if(df, is.numeric, janitor::round_half_up, digits = 2)
}

# set seed for reproducibility
set.seed(42)

```

# Data

## Item level data

```{r}

data_processed_itemlevel <- read_csv("../../../data/processed/bainbridge et al/data_processed_itemlevel.csv") 

```

## Nest item level data

### By subscale

```{r}

# subset_data <- function(data, string){
#   data |> 
#     select(starts_with(string), -contains("subscale")) |> 
#     drop_na()
# }
# 
# # bfi_o
# # bfi_c
# # bfi_e
# # bfi_a
# # bfi_n
# # ip_o
# # ip_c
# # ip_e
# # ip_a
# # ip_n
# # aggr_a
# # aggr_h
# # aggr_p
# # aggr_v
# # ambig
# # curi_e 
# # curi_f
# # doc_l
# # doc_da
# # doc_d 
# # dogma
# # dtmach
# # dtnarc
# # dtpsyc
# # empa
# # flour
# # gratit
# # grit_c
# # grit_p
# # hope_a
# # hope_p
# # iuncr
# # lone_e
# # lone_s
# # nfs_d
# # nfs_r
# # satwl
# # scpri
# # scpub 
# # scsanx
# # scont
# # seff
# # sest
# # vital
# # bas_d
# # bas_fs
# # bas_r
# # bis
# # erreap
# # ersup
# # empec
# # empf
# # emppd
# # emppt
# # imp_a
# # imp_m
# # imp_np
# # mndfn
# # nfc
# # opt
# # pain_h
# # pain_m
# # pain_r
# # pwb_a
# # pwb_em
# # pwb_pg
# # pwb_pr
# # pwb_pl
# # pwb_sa
# # scomp
# # smast
# # ss_fam
# # ss_fr
# # ss_so
# # worry
# # mlpres_mlpres
# # mlsrch_mlsrch
# 
# data_bfi_o <- subset_data(data_processed_itemlevel, "bfi_o")
# data_bfi_c <- subset_data(data_processed_itemlevel, "bfi_c")
# data_bfi_e <- subset_data(data_processed_itemlevel, "bfi_e")
# data_bfi_a <- subset_data(data_processed_itemlevel, "bfi_a")
# data_bfi_n <- subset_data(data_processed_itemlevel, "bfi_n")
# data_ip_o <- subset_data(data_processed_itemlevel, "ip_o")
# data_ip_c <- subset_data(data_processed_itemlevel, "ip_c")
# data_ip_e <- subset_data(data_processed_itemlevel, "ip_e")
# data_ip_a <- subset_data(data_processed_itemlevel, "ip_a")
# data_ip_n <- subset_data(data_processed_itemlevel, "ip_n")
# data_aggr_a <- subset_data(data_processed_itemlevel, "aggr_a")
# data_aggr_h <- subset_data(data_processed_itemlevel, "aggr_h")
# data_aggr_p <- subset_data(data_processed_itemlevel, "aggr_p")
# data_aggr_v <- subset_data(data_processed_itemlevel, "aggr_v")
# data_ambig <- subset_data(data_processed_itemlevel, "ambig")
# data_curi_e <- subset_data(data_processed_itemlevel, "curi_e ") 
# data_curi_f <- subset_data(data_processed_itemlevel, "curi_f")
# data_doc_l <- subset_data(data_processed_itemlevel, "doc_l")
# data_doc_da <- subset_data(data_processed_itemlevel, "doc_da")
# data_doc_d <- subset_data(data_processed_itemlevel, "doc_d ") 
# data_dogma <- subset_data(data_processed_itemlevel, "dogma")
# data_dtmach <- subset_data(data_processed_itemlevel, "dtmach")
# data_dtnarc <- subset_data(data_processed_itemlevel, "dtnarc")
# data_dtpsyc <- subset_data(data_processed_itemlevel, "dtpsyc")
# data_empa <- subset_data(data_processed_itemlevel, "empa")
# data_flour <- subset_data(data_processed_itemlevel, "flour")
# data_gratit <- subset_data(data_processed_itemlevel, "gratit")
# data_grit_c <- subset_data(data_processed_itemlevel, "grit_c")
# data_grit_p <- subset_data(data_processed_itemlevel, "grit_p")
# data_hope_a <- subset_data(data_processed_itemlevel, "hope_a")
# data_hope_p <- subset_data(data_processed_itemlevel, "hope_p")
# data_iuncr <- subset_data(data_processed_itemlevel, "iuncr")
# data_lone_e <- subset_data(data_processed_itemlevel, "lone_e")
# data_lone_s <- subset_data(data_processed_itemlevel, "lone_s")
# data_nfs_d <- subset_data(data_processed_itemlevel, "nfs_d")
# data_nfs_r <- subset_data(data_processed_itemlevel, "nfs_r")
# data_satwl <- subset_data(data_processed_itemlevel, "satwl")
# data_scpri <- subset_data(data_processed_itemlevel, "scpri")
# data_scpub <- subset_data(data_processed_itemlevel, "scpub ") 
# data_scsanx <- subset_data(data_processed_itemlevel, "scsanx")
# data_scont <- subset_data(data_processed_itemlevel, "scont")
# data_seff <- subset_data(data_processed_itemlevel, "seff")
# data_sest <- subset_data(data_processed_itemlevel, "sest")
# data_vital <- subset_data(data_processed_itemlevel, "vital")
# data_bas_d <- subset_data(data_processed_itemlevel, "bas_d")
# data_bas_fs <- subset_data(data_processed_itemlevel, "bas_fs")
# data_bas_r <- subset_data(data_processed_itemlevel, "bas_r")
# data_bis <- subset_data(data_processed_itemlevel, "bis")
# data_erreap <- subset_data(data_processed_itemlevel, "erreap")
# data_ersup <- subset_data(data_processed_itemlevel, "ersup")
# data_empec <- subset_data(data_processed_itemlevel, "empec")
# data_empf <- subset_data(data_processed_itemlevel, "empf")
# data_emppd <- subset_data(data_processed_itemlevel, "emppd")
# data_emppt <- subset_data(data_processed_itemlevel, "emppt")
# data_imp_a <- subset_data(data_processed_itemlevel, "imp_a")
# data_imp_m <- subset_data(data_processed_itemlevel, "imp_m")
# data_imp_np <- subset_data(data_processed_itemlevel, "imp_np")
# data_mndfn <- subset_data(data_processed_itemlevel, "mndfn")
# data_nfc <- subset_data(data_processed_itemlevel, "nfc")
# data_opt <- subset_data(data_processed_itemlevel, "opt")
# data_pain_h <- subset_data(data_processed_itemlevel, "pain_h")
# data_pain_m <- subset_data(data_processed_itemlevel, "pain_m")
# data_pain_r <- subset_data(data_processed_itemlevel, "pain_r")
# data_pwb_a <- subset_data(data_processed_itemlevel, "pwb_a")
# data_pwb_em <- subset_data(data_processed_itemlevel, "pwb_em")
# data_pwb_pg <- subset_data(data_processed_itemlevel, "pwb_pg")
# data_pwb_pr <- subset_data(data_processed_itemlevel, "pwb_pr")
# data_pwb_pl <- subset_data(data_processed_itemlevel, "pwb_pl")
# data_pwb_sa <- subset_data(data_processed_itemlevel, "pwb_sa")
# data_scomp <- subset_data(data_processed_itemlevel, "scomp")
# data_smast <- subset_data(data_processed_itemlevel, "smast")
# data_ss_fam <- subset_data(data_processed_itemlevel, "ss_fam")
# data_ss_fr <- subset_data(data_processed_itemlevel, "ss_fr")
# data_ss_so <- subset_data(data_processed_itemlevel, "ss_so")
# data_worry <- subset_data(data_processed_itemlevel, "worry")
# data_mlpres_mlpres <- subset_data(data_processed_itemlevel, "mlpres_mlpres")
# data_mlsrch_mlsrch <- subset_data(data_processed_itemlevel, "mlsrch_mlsrch")
# 
# data_nested <- 
#   bind_rows(
#     nest(data_bfi_o, data = everything()),
#     nest(data_bfi_c, data = everything()),
#     nest(data_bfi_e, data = everything()),
#     nest(data_bfi_a, data = everything()),
#     nest(data_bfi_n, data = everything()),
#     nest(data_ip_o, data = everything()),
#     nest(data_ip_c, data = everything()),
#     nest(data_ip_e, data = everything()),
#     nest(data_ip_a, data = everything()),
#     nest(data_ip_n, data = everything()),
#     nest(data_aggr_a, data = everything()),
#     nest(data_aggr_h, data = everything()),
#     nest(data_aggr_p, data = everything()),
#     nest(data_aggr_v, data = everything()),
#     nest(data_ambig, data = everything()),
#     nest(data_curi_e, data = everything()),
#     nest(data_curi_f, data = everything()),
#     nest(data_doc_l, data = everything()),
#     nest(data_doc_da, data = everything()),
#     nest(data_doc_d, data = everything()),
#     nest(data_dogma, data = everything()),
#     nest(data_dtmach, data = everything()),
#     nest(data_dtnarc, data = everything()),
#     nest(data_dtpsyc, data = everything()),
#     nest(data_empa, data = everything()),
#     nest(data_flour, data = everything()),
#     nest(data_gratit, data = everything()),
#     nest(data_grit_c, data = everything()),
#     nest(data_grit_p, data = everything()),
#     nest(data_hope_a, data = everything()),
#     nest(data_hope_p, data = everything()),
#     nest(data_iuncr, data = everything()),
#     nest(data_lone_e, data = everything()),
#     nest(data_lone_s, data = everything()),
#     nest(data_nfs_d, data = everything()),
#     nest(data_nfs_r, data = everything()),
#     nest(data_satwl, data = everything()),
#     nest(data_scpri, data = everything()),
#     nest(data_scpub, data = everything()),
#     nest(data_scsanx, data = everything()),
#     nest(data_scont, data = everything()),
#     nest(data_seff, data = everything()),
#     nest(data_sest, data = everything()),
#     nest(data_vital, data = everything()),
#     nest(data_bas_d, data = everything()),
#     nest(data_bas_fs, data = everything()),
#     nest(data_bas_r, data = everything()),
#     nest(data_bis, data = everything()),
#     nest(data_erreap, data = everything()),
#     nest(data_ersup, data = everything()),
#     nest(data_empec, data = everything()),
#     nest(data_empf, data = everything()),
#     nest(data_emppd, data = everything()),
#     nest(data_emppt, data = everything()),
#     nest(data_imp_a, data = everything()),
#     nest(data_imp_m, data = everything()),
#     nest(data_imp_np, data = everything()),
#     nest(data_mndfn, data = everything()),
#     nest(data_nfc, data = everything()),
#     nest(data_opt, data = everything()),
#     nest(data_pain_h, data = everything()),
#     nest(data_pain_m, data = everything()),
#     nest(data_pain_r, data = everything()),
#     nest(data_pwb_a, data = everything()),
#     nest(data_pwb_em, data = everything()),
#     nest(data_pwb_pg, data = everything()),
#     nest(data_pwb_pr, data = everything()),
#     nest(data_pwb_pl, data = everything()),
#     nest(data_pwb_sa, data = everything()),
#     nest(data_scomp, data = everything()),
#     nest(data_smast, data = everything()),
#     nest(data_ss_fam, data = everything()),
#     nest(data_ss_fr, data = everything()),
#     nest(data_ss_so, data = everything()),
#     nest(data_worry, data = everything()),
#     nest(data_mlpres_mlpres, data = everything()),
#     nest(data_mlsrch_mlsrch, data = everything())
#   ) |>
#   mutate(scale = c("bfi_o", "bfi_c", "bfi_e", "bfi_a", "bfi_n", "ip_o", "ip_c", "ip_e", "ip_a", "ip_n", "aggr_a", "aggr_h", "aggr_p", "aggr_v", "ambig", "curi_e", "curi_f", "doc_l", "doc_da", "doc_d", "dogma", "dtmach", "dtnarc", "dtpsyc", "empa", "flour", "gratit", "grit_c", "grit_p", "hope_a", "hope_p", "iuncr", "lone_e", "lone_s", "nfs_d", "nfs_r", "satwl", "scpri", "scpub", "scsanx", "scont", "seff", "sest", "vital", "bas_d", "bas_fs", "bas_r", "bis", "erreap", "ersup", "empec", "empf", "emppd", "emppt", "imp_a", "imp_m", "imp_np", "mndfn", "nfc", "opt", "pain_h", "pain_m", "pain_r", "pwb_a", "pwb_em", "pwb_pg", "pwb_pr", "pwb_pl", "pwb_sa", "scomp", "smast", "ss_fam", "ss_fr", "ss_so", "worry", "mlpres_mlpres", "mlsrch_mlsrch")) |>
#   select(scale, data)

```

### By scale except for BFI and IP

```{r}

subset_data <- function(data, string){
  data |> 
    select(starts_with(string), -contains("subscale")) |> 
    drop_na()
}

# aggr
# ambig
# bas
# bfi_a
# bfi_c
# bfi_e
# bfi_n
# bfi_o
# bis
# curi
# doc
# dogma
# dt
# empa
# er
# flour
# gratit
# grit
# hope
# imp
# ip_a
# ip_c
# ip_e
# ip_n
# ip_o
# iuncr
# lone
# mlpres
# mndfn
# nfc
# nfs
# opt
# pain
# pwb
# satwl
# scomp
# seff
# sest
# smast
# ss
# vital
# worry

data_aggr <- subset_data(data_processed_itemlevel, "aggr")
data_ambig <- subset_data(data_processed_itemlevel, "ambig")
data_bas <- subset_data(data_processed_itemlevel, "bas")
data_bfi_a <- subset_data(data_processed_itemlevel, "bfi_a")
data_bfi_c <- subset_data(data_processed_itemlevel, "bfi_c")
data_bfi_e <- subset_data(data_processed_itemlevel, "bfi_e")
data_bfi_n <- subset_data(data_processed_itemlevel, "bfi_n")
data_bfi_o <- subset_data(data_processed_itemlevel, "bfi_o")
data_bis <- subset_data(data_processed_itemlevel, "bis")
data_curi <- subset_data(data_processed_itemlevel, "curi")
data_doc <- subset_data(data_processed_itemlevel, "doc")
data_dogma <- subset_data(data_processed_itemlevel, "dogma")
data_dt <- subset_data(data_processed_itemlevel, "dt")
data_empa <- subset_data(data_processed_itemlevel, "empa")
data_er <- subset_data(data_processed_itemlevel, "er")
data_flour <- subset_data(data_processed_itemlevel, "flour")
data_gratit <- subset_data(data_processed_itemlevel, "gratit")
data_grit <- subset_data(data_processed_itemlevel, "grit")
data_hope <- subset_data(data_processed_itemlevel, "hope")
data_imp <- subset_data(data_processed_itemlevel, "imp")
data_ip_a <- subset_data(data_processed_itemlevel, "ip_a")
data_ip_c <- subset_data(data_processed_itemlevel, "ip_c")
data_ip_e <- subset_data(data_processed_itemlevel, "ip_e")
data_ip_n <- subset_data(data_processed_itemlevel, "ip_n")
data_ip_o <- subset_data(data_processed_itemlevel, "ip_o")
data_iuncr <- subset_data(data_processed_itemlevel, "iuncr")
data_lone <- subset_data(data_processed_itemlevel, "lone")
data_mlpres <- subset_data(data_processed_itemlevel, "mlpres")
data_mndfn <- subset_data(data_processed_itemlevel, "mndfn")
data_nfc <- subset_data(data_processed_itemlevel, "nfc")
data_nfs <- subset_data(data_processed_itemlevel, "nfs")
data_opt <- subset_data(data_processed_itemlevel, "opt")
data_pain <- subset_data(data_processed_itemlevel, "pain")
data_pwb <- subset_data(data_processed_itemlevel, "pwb")
data_satwl <- subset_data(data_processed_itemlevel, "satwl")
data_scomp <- subset_data(data_processed_itemlevel, "scomp")
data_seff <- subset_data(data_processed_itemlevel, "seff")
data_sest <- subset_data(data_processed_itemlevel, "sest")
data_smast <- subset_data(data_processed_itemlevel, "smast")
data_ss <- subset_data(data_processed_itemlevel, "ss")
data_vital <- subset_data(data_processed_itemlevel, "vital")
data_worry <- subset_data(data_processed_itemlevel, "worry")


data_nested <- 
  bind_rows(
    nest(data_aggr, data = everything()),
    nest(data_ambig, data = everything()),
    nest(data_bas, data = everything()),
    nest(data_bis, data = everything()),
    nest(data_bfi_a, data = everything()),
    nest(data_bfi_c, data = everything()),
    nest(data_bfi_e, data = everything()),
    nest(data_bfi_n, data = everything()),
    nest(data_bfi_o, data = everything()),
    nest(data_curi, data = everything()),
    nest(data_doc, data = everything()),
    nest(data_dogma, data = everything()),
    nest(data_dt, data = everything()),
    nest(data_empa, data = everything()),
    nest(data_er, data = everything()),
    nest(data_flour, data = everything()),
    nest(data_gratit, data = everything()),
    nest(data_grit, data = everything()),
    nest(data_hope, data = everything()),
    nest(data_imp, data = everything()),
    nest(data_ip_a, data = everything()),
    nest(data_ip_c, data = everything()),
    nest(data_ip_e, data = everything()),
    nest(data_ip_n, data = everything()),
    nest(data_ip_o, data = everything()),
    nest(data_iuncr, data = everything()),
    nest(data_lone, data = everything()),
    nest(data_mlpres, data = everything()),
    nest(data_mndfn, data = everything()),
    nest(data_nfc, data = everything()),
    nest(data_nfs, data = everything()),
    nest(data_opt, data = everything()),
    nest(data_pain, data = everything()),
    nest(data_pwb, data = everything()),
    nest(data_satwl, data = everything()),
    nest(data_scomp, data = everything()),
    nest(data_seff, data = everything()),
    nest(data_sest, data = everything()),
    nest(data_smast, data = everything()),
    nest(data_ss, data = everything()),
    nest(data_vital, data = everything()),
    nest(data_worry, data = everything())
  ) |>
  mutate(scale = c("aggr", "ambig", "bas", "bfi_a", "bfi_c", "bfi_e", "bfi_n", "bfi_o", "bis", "curi", 
                   "doc", "dogma", "dt", "empa", "er", "flour", "gratit", "grit", "hope", 
                   "imp", "ip_a", "ip_c", "ip_e", "ip_n", "ip_o", "iuncr", "lone", "mlpres", "mndfn", 
                   "nfc", "nfs", "opt", "pain", "pwb", "satwl", "scomp", "seff", "sest", 
                   "smast", "ss", "vital", "worry")) |>
  select(scale, data)

```

# Write to disk

```{r}

write_rds(data_nested, "../../../data/processed/bainbridge et al/data_nested.rds")

```

# Session info

```{r}

sessionInfo()

```



