
# original

```{r}


# All feedback welcome
# Fred Oswald
# Professor, Rice University
# https://workforce.rice.edu
# foswald@rice.edu
library(corrplot)
m1 <- matrix(c(1, .1, .1, .3, .3, .3,
               .1, 1, .1, .3, .3, .3,
               .1, .1, 1, .3, .3, .3,
               .3, .3, .3, 1, .5, .5,
               .3, .3, .3, .5, 1, .5,
               .3, .3, .3, .5, .5, 1),nrow=6)
rownames(m1) <- colnames(m1) <- c("x1","x2","x3","x4","x5", "x6")
corrplot(m1, method="square",addCoef.col = 1,col = colorRampPalette(c("red", "white", "deepskyblue"))(100),tl.cex=1,cl.cex=1,)

m2 <- matrix(c(1, .3, .3, .3, .3, .3,
               .3, 1, .3, .3, .3, .3,
               .3, .3, 1, .3, .3, .3,
               .3, .3, .3, 1, .3, .3,
               .3, .3, .3, .3, 1, .3,
               .3, .3, .3, .3, .3, 1),nrow=6)
rownames(m2) <- colnames(m2) <- c("x1","x2","x3","x4","x5", "x6")
corrplot(m2, method="square",addCoef.col = 1,col = colorRampPalette(c("red", "white", "deepskyblue"))(100),tl.cex=1,cl.cex=1,)

m3 <- matrix(c(1, -.1, -.1, .3, .3, .3,
               -.1, 1, -.1, .3, .3, .3,
               -.1, -.1, 1, .3, .3, .3,
               .3, .3, .3, 1, .7, .7,
               .3, .3, .3, .7, 1, .7,
               .3, .3, .3, .7, .7, 1),nrow=6)
rownames(m3) <- colnames(m3) <- c("x1","x2","x3","x4","x5", "x6")
corrplot(m3, method="square",addCoef.col = 1,col = colorRampPalette(c("red", "white", "deepskyblue"))(100),tl.cex=1,cl.cex=1,)

m4 <- matrix(c(1, .8, .8, .0, .0, .0,
               .8 , 1, .7, .0, .0, .0,
               .8, .7, 1, .0, .0, .0,
               .0, .0, .0, 1, .7, .7,
               .0, .0, .0, .7, 1, .8,
               .0, .0, .0, .7, .8, 1),nrow=6)
rownames(m4) <- colnames(m4) <- c("x1","x2","x3","x4","x5", "x6")
corrplot(m4, method="square",addCoef.col = 1,col = colorRampPalette(c("red", "white", "deepskyblue"))(100),tl.cex=1,cl.cex=1,)


```

# mod

```{r}


# All feedback welcome
# Fred Oswald
# Professor, Rice University
# https://workforce.rice.edu
# foswald@rice.edu
library(corrplot)
library(viridis)

colors <- viridis(n = 3, begin = 0.2, end = 0.8, option = "mako")

m1 <- matrix(c(1, .3, .3, .3, .3, .3,
               .3, 1, .3, .3, .3, .3,
               .3, .3, 1, .3, .3, .3,
               .3, .3, .3, 1, .3, .3,
               .3, .3, .3, .3, 1, .3,
               .3, .3, .3, .3, .3, 1),nrow=6)
rownames(m1) <- colnames(m1) <- c("x1","x2","x3","x4","x5","x6")
corrplot(m1,
         method = "square", 
         addCoef.col = 1,
         diag = TRUE,
         outline = FALSE,
         type = "lower",
         col = colorRampPalette(c(colors[1], colors[2], colors[3]))(100),
         tl.cex = 1,
         cl.cex = 1,
         tl.col = "black",
         tl.srt = 0,
         tl.offset = .8,
         number.font = 1)

m1_mean_r <- mean(m1[lower.tri(m1)])
m1_mean_r

m1_alpha <- psych::alpha(m1)$total$raw_alpha
m1_alpha

```


```{r}

m2 <- matrix(c(1, -.1, -.1, .3, .3, .3,
               -.1, 1, -.1, .3, .3, .3,
               -.1, -.1, 1, .3, .3, .3,
               .3, .3, .3, 1, .7, .7,
               .3, .3, .3, .7, 1, .7,
               .3, .3, .3, .7, .7, 1),nrow=6)
rownames(m2) <- colnames(m2) <- c("x1","x2","x3","x4","x5","x6")
corrplot(m2, 
         method = "square", 
         addCoef.col = 1,
         diag = TRUE,
         outline = FALSE,
         type = "lower",
         col = colorRampPalette(c(colors[1], colors[2], colors[3]))(100),
         tl.cex = 1,
         cl.cex = 1,
         tl.col = "black",
         tl.srt = 0,
         tl.offset = .8,
         number.font = 1)

m2_mean_r <- mean(m1[lower.tri(m1)])
m2_mean_r

m2_alpha <- psych::alpha(m2)
m2_alpha$total$raw_alpha

```



```{r}

library(MASS)

n <- 100

simulate_data <- function(n, mat){
  as_tibble(MASS::mvrnorm(
    n = n,
    mu = rep(0, nrow(mat)),
    Sigma = mat, 
  )) 
}

# |>
#   rownames_to_column(var = "id") 
# |>
#   pivot_longer(cols = -id) |>
#   group_by(id) |>
#   summarize(score = mean(value))


data_simulated <- 
  nest(simulate_data(n = 100, mat = m1), data = everything()) |>
  rownames_to_column(var = "iteration")


data_simulated <- 
  tibble(iter = seq(1, 100)) |>
  mutate(data = purrr::map(simulate_data, n = 100, mat = m1))





iterations_vector <- seq(1, 10)

sim_data <- function(n, mat){
  
  res <- 
    lapply(
      seq_along(iterations_vector), 
      function(...){
        as_tibble(MASS::mvrnorm(
          n = n,
          mu = rep(0, nrow(mat)),
          Sigma = mat, 
        )) 
      }
    ) |>
    dplyr::bind_rows() |>
    mutate(iter = iterations_vector[[i]]
  
  return(res)  
} 

results <- sim_data(n = 100, mat = m1)
  

```




